dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
- rm local_settings.py
deploy:
  provider: heroku
  app: decide-travis-javdecab
  strategy: git
  api_key:
    secure: M3PGaiNZ7Bi12X56njlDlc5RVpMaQJPHdRQtSqZhhZt2kIUKBhuWDLP5YVkwgWc4ztj75qK5r/kEQIU6eNDa5LJXz5hv/Z5GvOmnsfgKnLkTtNWXx4Q1H23mH3nZoX0pXIX2bUnFguzgJl/JHpXFIdNbtL578Ra3jRQDjlFH1LM5akTrUNeQ4gSAKcpSZNG+J33DdFU37ERNUaRp5JZoU96VePHSLmm5kDlQ2vp594tRM3a91AKOdl/2xlEqj3m0t/JT/tbN9EmcjU02xS7fkzN9oEt0WXVrUs3PYMRDJvcmJpNTyZzMxX/X1lhEx8ZQ+Bk71a6qflMLl+bEn/f4REo27Y6HoC/xdH1JbBozNjV7XgpVjgkUe42uAE/lWQ3bvyc5zc4CacgHW0mKiJnBK0KI38B/a8H17AVuQu9SwQ8X88m2Jg7mTBEDxRsuQxXzWo421nCTd9pCS1BohjxCCrdrN05YqnXNudbwg7ZOwKMegAvtaYDORQKjM5OTKAS3WbB7AN5uCkT+gJFxRCANHV1d7hPIfhiNlCr16CHtMQQXefVG7QKFjtN5fOmNZUdONNxTLVjcXj/Fp9mdDuOO2QT+MQuyMiThbyg1mTVaVm7cZy7bV4MsfmQGU+cMeQq71BNfAZDbNhcC0GE6/Y+t1doRVpwsPlprR8+BLXctIkc=
